sudo: required
language: node_js
cache:
  npm: false
node_js:
- lts/*
before_script:
- npm install -g grunt-cli npm
env:
  matrix:
  - CXX="g++-4.8"
  global:
    secure: EW8wQ4ZTe859edhfgDplSKP/VLBLOkuU4uDiIY9sP4Wg/b+T0B4py9DPOZQUXhx6iBg87gZAHZMPGiJCj+4fWsQYlImAfgSZ6kq9O7a/dsIp8zWQD4IFc8TVDYW262AesUPjDMH+U7ynzH11PkCHVgjT8dioWCtDYf7sjn7Iyo//4xC4PF4OhHmsjsE53OBdnNknqT3z5LIc5s3UypGdLM6QSgz1a7XEgjmcOsx8+Z6ZWeIwRBHleJ/th95B5rTbb2AC5U4Q8FxX15EsLlc8NRn02wi7EVg45gEdl5KmdTWI3ZEdkvEJVAyu5Nm72ouGNiwSeDpcKc7ciRDCw6kGFLvdw6BbjPtlzCTFXX2P4JQc/RY+asA/95CjsIxjVQHUZhS8yWDUwyd46h3mI74OmXY/p48ueDPvK3ZBI2GC1WOg3A7L1grfcWC8nQjaCd8Ry+7RVXb4hI5b9+v27SuS+e9cTfDcyIg37wBPblP08MCVFvTstdwzMtl6CbHe/IpFIBirfg/zVa6nlp7XoRToBA72hVL8HqNGmf4XAt/UKTvaS/feUHJqrRDolXu1xzr9yWzoHC75mPVqfx+R571UB5UNIUZGKNM7z1jELodYWy9xw1EgD6qNwiI2/QNxxkz2xeHRYXRjBtb83eJMI5IrdB6lxB9IvZsXCPa8K94codA=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8
