sudo: required
language: node_js
cache:
    npm: false
node_js:
    - node
before_script:
    - npm install -g grunt-cli npm
env:
    - CXX="g++-4.8"
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
            - gcc-4.8
